AppAccounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from .views import edit_profile

app_name = 'AppAccounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.signup_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('edit-profile/', views.edit_profile_view, name='edit_profile'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change_password'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('edit-profile/', edit_profile, name="edit_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppBlog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'AppBlog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),  # Listado de posts
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),  # Detalle de un post
    path('create/', PostCreateView.as_view(), name='create'),  # Crear un post
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),  # Editar un post
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),  # Borrar un post
    
]

AppMessages/urls.py
from django.urls import path
from .views import InboxView, MessageDetailView, SendMessageView

app_name = 'AppMessages'

urlpatterns = [
    path('inbox/', InboxView, name='inbox'),
    path('message/<int:message_id>/', MessageDetailView, name='message_detail'),
    path('send/', SendMessageView, name='send_message'),
]

MiProyecto/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from AppCoder import views as appcoder_views

urlpatterns = [
    path('', appcoder_views.index, name='index'),
    path('superadmin/', admin.site.urls),
    path('', include('AppCoder.urls')),
    path('blog/', include('AppBlog.urls')),
    path('messages/', include('AppMessages.urls', namespace='AppMessages')),
    path('accounts/', include('AppAccounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8"> <!-- Define la codificación de caracteres para admitir acentos y caracteres especiales -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Hace que el diseño sea responsive -->
    <title>{% block titulo %}AppCoder - Inicio{% endblock %}</title> <!-- Permite personalizar el título en cada página -->
    
    <!-- Carga Bootstrap desde un CDN para el diseño responsive -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    
    {% load static %} <!-- Habilita el uso de archivos estáticos en Django -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Carga la hoja de estilos personalizada -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #343a40;">
        <div id="navbarNav">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <!-- Determina qué nombre mostrar según la URL activa -->
                    <a class="nav-link active bg-success {% if request.resolver_match.url_name == 'index' %}{% endif %}" aria-current="page" href="{% url 'index' %}">
                        {% if request.resolver_match.url_name in 'index,acerca,contacto' %}
                        AppCoder
                        {% elif request.resolver_match.url_name in 'lista_socios,cargar_socio' %}
                        Socios
                        {% elif request.resolver_match.url_name in 'lista_instructores,cargar_instructor' %}
                        Instructores
                        {% elif request.resolver_match.url_name in 'cargar_actividad,lista_actividades' %}
                        Actividad
                        {% elif request.resolver_match.url_name in 'list,create,detail,update,delete' %}
                        Blog
                        {% elif request.resolver_match.url_name in 'inbox,message_detail,send_message' %}
                        Mensajes
                        {% elif request.resolver_match.url_name in 'login,edit_profile,change_password,profile,signup,register' %}
                        Usuario
                        {% else %}
                        App{{ request.resolver_match.url_name|capfirst }}
                        {% endif %}
                    </a>
                </li>
                
                <!-- Menú desplegable para Socios -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color: #d6d6d6;">Socios</a>
                    <ul class="dropdown-menu dropdown-menu-custom">
                        <li><a class="dropdown-item" href="{% url 'cargar_socio' %}">Agregar Socio</a></li>
                        <li><a class="dropdown-item" href="{% url 'lista_socios' %}">Lista Socios</a></li>
                    </ul>
                </li>

                <!-- Menú desplegable para Instructores -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color: #d6d6d6;">Instructores</a>
                    <ul class="dropdown-menu dropdown-menu-custom">
                        <li><a class="dropdown-item" href="{% url 'cargar_instructor' %}">Agregar Instructor</a></li>
                        <li><a class="dropdown-item" href="{% url 'lista_instructores' %}">Lista Instructores</a></li>
                    </ul>
                </li>

                <!-- Menú desplegable para Actividades -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color: #d6d6d6;">Actividades</a>
                    <ul class="dropdown-menu dropdown-menu-custom">
                        <li><a class="dropdown-item" href="{% url 'cargar_actividad' %}">Crear Actividad</a></li>
                        <li><a class="dropdown-item" href="{% url 'lista_actividades' %}">Lista de Actividades</a></li>
                    </ul>
                </li>

                <!-- Enlace al Blog -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'AppBlog:list' %}" style="color: #d6d6d6;">Blog</a>
                </li>

                <!-- Mensajes con indicador de no leídos -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color: #d6d6d6;">
                    Mensajes {% if unread_count > 0 %}<span class="badge">{{ unread_count }}</span>{% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-custom">
                        <li><a class="dropdown-item" href="{% url 'AppMessages:inbox' %}">Mensajes</a></li>
                        <li><a class="dropdown-item" href="{% url 'AppMessages:send_message' %}">Mensajes enviados</a></li>
                    </ul>
                </li>

                <!-- Enlaces estáticos -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'acerca' %}" style="color: #d6d6d6;">Acerca</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacto' %}" style="color: #d6d6d6;">Contacto</a>
                </li>
            </ul>
        </div>

        <!-- Sección de usuario (autenticación) -->
        <div class="ms-auto">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <span class="text-white">{{ user.username }}</span>
                    <img class="img-login" src="{{ user.profile.avatar.url|default:'/media/avatars/avataruser.png' }}" alt="Avatar">
                    <li><a class="nav-link" href="{% url 'AppAccounts:profile' %}" style="color: #d6d6d6;">Perfil</a></li>
                    <li><a class="nav-link" href="{% url 'AppAccounts:logout' %}" style="color: #d6d6d6;">Logout</a></li>
                    {% if user.is_staff %}
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                    {% endif %}
                {% else %}
                    <li><a class="nav-link" href="{% url 'AppAccounts:login' %}" style="color: #d6d6d6;">Login</a></li>
                    <li><a class="nav-link" href="{% url 'AppAccounts:register' %}" style="color: #d6d6d6;">Signup</a></li>
                {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <!-- Muestra mensajes de Django (notificaciones) -->
    {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    {% block cuerpo %}{% endblock %} <!-- Bloque donde se cargará el contenido específico de cada página -->

    <footer class="footer">
        <p>&copy; 2025 AppCoder - Todos los derechos reservados</p>
    </footer>

    <!-- Carga el script de Bootstrap para funcionalidades interactivas -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    
    <script>
        // Espera a que la página cargue y oculta los mensajes de éxito después de 3 segundos
        document.addEventListener('DOMContentLoaded', function() {
            const alerts = document.querySelectorAll('.alert-container .alert');
            if (alerts.length > 0) {
                setTimeout(() => {
                    alerts.forEach(alert => {
                        alert.style.display = 'none';
                    });
                }, 3000);
            }
        });
    </script>
</body>
</html>

templates/base_login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}AppCoder - Inicio{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #343a40;">
        <div id="navbarNav">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link active bg-success {% if request.resolver_match.url_name == 'index' %}{% endif %}" aria-current="page" href="{% url 'index' %}">
                        {% if request.resolver_match.url_name in 'index,acerca,contacto' %}
                        AppCoder
                        {% elif request.resolver_match.url_name in 'lista_socios,cargar_socio' %}
                        Socios
                        {% elif request.resolver_match.url_name in 'lista_instructores,cargar_instructor' %}
                        Instructores
                        {% elif request.resolver_match.url_name in 'cargar_actividad,lista_actividades' %}
                        Actividad
                        {% elif request.resolver_match.url_name in 'list,create,detail,update,delete' %}
                        Blog
                        {% elif request.resolver_match.url_name in 'inbox,message_detail,send_message' %}
                        Mensajes
                        {% elif request.resolver_match.url_name in 'login,edit_profile,change_password,profile,signup,register' %}
                        Usuario
                        {% else %}
                        App{{ request.resolver_match.url_name|capfirst }}
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
        <div class="ms-auto">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <span class="text-white">{{ user.username }}</span>
                    <img class="img-login" src="{{ user.profile.avatar.url|default:'/media/avatars/avataruser.png' }}" alt="Avatar">
                    <li><a class="nav-link" href="{% url 'AppAccounts:profile' %}" style="color: #d6d6d6;">Perfil</a></li>
                    <li><a class="nav-link"href="{% url 'AppAccounts:logout' %}" style="color: #d6d6d6;">Logout</a></li>
                    {% if user.is_staff %}
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                    {% endif %}
                {% else %}
                    <li><a class="nav-link" href="{% url 'AppAccounts:register' %}" style="color: #d6d6d6;">Signup</a></li>
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                {% endif %}
                </li>
                </li>
            </ul>
        </div>
    </nav>
    {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    {% block cuerpo %}


    {% endblock %}
    <footer class="footer">
        <p>&copy; 2025 AppCoder - Todos los derechos reservados</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        setTimeout(function() {
            var alert = document.querySelector('.alert');
            if (alert) {
                alert.classList.remove('show');
            }
        }, 5000);  // Los mensajes desaparecerán después de 5 segundos
    </script>
</body>
</html>

templates/base_perfil.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}AppCoder - Inicio{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #343a40;">
        <div id="navbarNav">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link active bg-success {% if request.resolver_match.url_name == 'index' %}{% endif %}" aria-current="page" href="{% url 'index' %}">
                        {% if request.resolver_match.url_name in 'index,acerca,contacto' %}
                        AppCoder
                        {% elif request.resolver_match.url_name in 'lista_socios,cargar_socio' %}
                        Socios
                        {% elif request.resolver_match.url_name in 'lista_instructores,cargar_instructor' %}
                        Instructores
                        {% elif request.resolver_match.url_name in 'cargar_actividad,lista_actividades' %}
                        Actividad
                        {% elif request.resolver_match.url_name in 'list,create,detail,update,delete' %}
                        Blog
                        {% elif request.resolver_match.url_name in 'inbox,message_detail,send_message' %}
                        Mensajes
                        {% elif request.resolver_match.url_name in 'login,edit_profile,change_password,profile,signup,register' %}
                        Usuario
                        {% else %}
                        App{{ request.resolver_match.url_name|capfirst }}
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
        <div class="ms-auto">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <span class="text-white">{{ user.username }}</span>
                    <img class="img-login" src="{{ user.profile.avatar.url|default:'/media/avatars/avataruser.png' }}" alt="Avatar">
                    <li><a class="nav-link" href="{% url 'AppAccounts:profile' %}" style="color: #d6d6d6;">Perfil</a></li>
                    <li><a class="nav-link"href="{% url 'AppAccounts:logout' %}" style="color: #d6d6d6;">Logout</a></li>
                    {% if user.is_staff %}
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                    {% endif %}
                {% else %}
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                {% endif %}
                </li>
                </li>
            </ul>
        </div>
    </nav>
    {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    {% block cuerpo %}
    {% endblock %}

    <footer class="footer">
        <p>&copy; 2025 AppCoder - Todos los derechos reservados</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        setTimeout(function() {
            var alert = document.querySelector('.alert');
            if (alert) {
                alert.classList.remove('show');
            }
        }, 5000);  // Los mensajes desaparecerán después de 5 segundos
    </script>
</body>
</html>

templates/base_signup.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}AppCoder - Inicio{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #343a40;">
        <div id="navbarNav">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link active bg-success {% if request.resolver_match.url_name == 'index' %}{% endif %}" aria-current="page" href="{% url 'index' %}">
                        {% if request.resolver_match.url_name in 'index,acerca,contacto' %}
                        AppCoder
                        {% elif request.resolver_match.url_name in 'lista_socios,cargar_socio' %}
                        Socios
                        {% elif request.resolver_match.url_name in 'lista_instructores,cargar_instructor' %}
                        Instructores
                        {% elif request.resolver_match.url_name in 'cargar_actividad,lista_actividades' %}
                        Actividad
                        {% elif request.resolver_match.url_name in 'list,create,detail,update,delete' %}
                        Blog
                        {% elif request.resolver_match.url_name in 'inbox,message_detail,send_message' %}
                        Mensajes
                        {% elif request.resolver_match.url_name in 'login,edit_profile,change_password,profile,signup,register' %}
                        Usuario
                        {% else %}
                        App{{ request.resolver_match.url_name|capfirst }}
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
        <div class="ms-auto">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <span class="text-white">{{ user.username }}</span>
                    <img class="img-login" src="{{ user.profile.avatar.url|default:'/media/avatars/avataruser.png' }}" alt="Avatar">
                    <li><a class="nav-link" href="{% url 'AppAccounts:profile' %}" style="color: #d6d6d6;">Perfil</a></li>
                    <li><a class="nav-link"href="{% url 'AppAccounts:logout' %}" style="color: #d6d6d6;">Logout</a></li>
                    {% if user.is_staff %}
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                    {% endif %}
                {% else %}
                    <li><a class="nav-link" href="{% url 'AppAccounts:login' %}" style="color: #d6d6d6;">Login</a></li>
                    <li><a class="nav-link" href='/superadmin/' style="color: #d6d6d6;">Admin</a></li>
                {% endif %}
                </li>
                </li>
            </ul>
        </div>
    </nav>
    {% if messages %}
    <div id="message-container">
        {% if messages %}
        <div class="alert-container">
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {% endif %}
    {% block cuerpo %}
    {% endblock %}

    <footer class="footer">
        <p>&copy; 2025 AppCoder - Todos los derechos reservados</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        setTimeout(function() {
            var alert = document.querySelector('.alert');
            if (alert) {
                alert.classList.remove('show');
            }
        }, 5000);  // Los mensajes desaparecerán después de 5 segundos
    </script>
</body>
</html>