AppAccounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from .views import edit_profile

app_name = 'AppAccounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.signup_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('edit-profile/', views.edit_profile_view, name='edit_profile'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change_password'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('edit-profile/', edit_profile, name="edit_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppBlog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'AppBlog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),  # Listado de posts
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),  # Detalle de un post
    path('create/', PostCreateView.as_view(), name='create'),  # Crear un post
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),  # Editar un post
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),  # Borrar un post
    
]

MiProyecto/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from AppCoder import views as appcoder_views

urlpatterns = [
    path('', appcoder_views.index, name='index'),
    path('superadmin/', admin.site.urls),
    path('', include('AppCoder.urls')),
    path('blog/', include('AppBlog.urls')),
    path('messages/', include('AppMessages.urls', namespace='AppMessages')),
    path('accounts/', include('AppAccounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppAccounts/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField

AVATAR_CHOICES = [
    ('avatars/avataruser.png', 'Avatar por defecto'),
    ('avatars/avatar1.png', 'Avatar 1'),
    ('avatars/avatar2.png', 'Avatar 2'),
    ('avatars/avatar3.png', 'Avatar 3'),
    ('avatars/avatar4.png', 'Avatar 4'),
    ('avatars/avatar5.png', 'Avatar 5'),
    ('avatars/avatar6.png', 'Avatar 6'),
    ('avatars/avatar7.png', 'Avatar 7'),
    ('avatars/avatar8.png', 'Avatar 8'),
    ('avatars/avatar9.png', 'Avatar 9'),
    ('avatars/avatar10.png', 'Avatar 10'),
    ('avatars/avatar11.png', 'Avatar 11'),
    ('avatars/avatar12.png', 'Avatar 12'),
    ('avatars/avatar13.png', 'Avatar 13'),
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/avataruser.png')
    bio = RichTextField(blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"

    def get_avatar_url(self):
        return f"/media/{self.avatar}"

AppAccounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from ckeditor.widgets import CKEditorWidget
from .models import Profile

# Formulario de registro de usuario
class UserRegistrationForm(forms.ModelForm):
    # Campos del formulario
    username = forms.CharField(label="Nombre de usuario", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label="Contraseña")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label="Repetir Contraseña")
    email = forms.EmailField(label="Correo", widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    # Guardar el usuario y crear perfil
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

# Formulario para editar perfil
class EditProfileForm(forms.ModelForm):
    # Campos del formulario
    first_name = forms.CharField(label="Nombre", widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    last_name = forms.CharField(label="Apellido", widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    
    # Opciones de avatar
    AVATAR_CHOICES = [
        ('avatars/avatar1.png', 'Avatar 1'),
        ('avatars/avatar2.png', 'Avatar 2'),
        ('avatars/avatar3.png', 'Avatar 3'),
        ('avatars/avatar4.png', 'Avatar 4'),
        ('avatars/avatar5.png', 'Avatar 5'),
        ('avatars/avatar6.png', 'Avatar 6'),
        ('avatars/avatar7.png', 'Avatar 7'),
        ('avatars/avatar8.png', 'Avatar 8'),
        ('avatars/avatar9.png', 'Avatar 9'),
        ('avatars/avatar10.png', 'Avatar 10'),
        ('avatars/avatar11.png', 'Avatar 11'),
        ('avatars/avatar12.png', 'Avatar 12'),
        ('avatars/avatar13.png', 'Avatar 13'),
    ]

    avatar = forms.ChoiceField(
        choices=AVATAR_CHOICES, 
        required=False, 
        widget=forms.RadioSelect
    )

    bio = forms.CharField(label="Biografia", widget=CKEditorWidget(), required=False)
    birthday = forms.DateField(label="Fecha de nacimiento", widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), required=False)
    address = forms.CharField(label="Dirección", widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    phone = forms.CharField(label="Telefono", widget=forms.TextInput(attrs={'class': 'form-control', 'pattern': '[0-9]{3}-[0-9]{3}-[0-9]{4}', 'placeholder': 'Ingresa tu numero personal: xxx-xxx-xxxx'}), required=False)

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'avatar', 'bio', 'birthday', 'address', 'phone']

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)

        # Inicializar campos con datos del usuario
        self.fields['first_name'].initial = self.instance.user.first_name
        self.fields['last_name'].initial = self.instance.user.last_name

        if self.instance.avatar:
            self.fields['avatar'].initial = self.instance.avatar

# Formulario de autenticación de perfil
class ProfileAuthenticationForm(AuthenticationForm):
    # Campos del formulario
    username = forms.CharField(label="Nombre de usuario", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password']

AppAccounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import AuthenticationForm
from .forms import ProfileAuthenticationForm, UserRegistrationForm, EditProfileForm 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import Profile
from django.conf import settings

def login_view(request):
    if request.method == "POST":
        form = ProfileAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # Mensaje de éxito
                messages.success(request, "¡Bienvenido, has iniciado sesión con éxito!")
                return redirect('index')  # Redirige al index después de iniciar sesión
            else:
                messages.error(request, "Usuario o contraseña incorrectos")
        else:
            messages.error(request, "Datos no válidos")
    else:
        form = ProfileAuthenticationForm()
    return render(request, 'Accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    # Mensaje de éxito
    messages.success(request, "¡Has cerrado sesión correctamente!")
    return redirect('index')  # Redirige al home

def index(request):
    return render(request, 'AppCoder/index.html')

def signup_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # Mensaje de éxito
            messages.success(request, "¡Te has registrado con éxito!")
            return redirect('index')  # Redirige al index después de registrarse
    else:
        form = UserRegistrationForm()
    return render(request, 'Accounts/signup.html', {'form': form})

@login_required
def profile_view(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'Accounts/profile.html', {'user': profile})

@login_required
def edit_profile_view(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            user = request.user
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            form.save()
            # Mensaje de éxito
            messages.success(request, "¡Perfil actualizado con éxito!")
            return redirect('AppAccounts:profile')  # Redirige al perfil después de guardar
    else:
        form = EditProfileForm(instance=request.user.profile)
    return render(request, 'Accounts/edit_profile.html', {'form': form})

def edit_profile(request):
    form = EditProfileForm(instance=request.user.profile)
    return render(request, "edit_perfil.html", {"form": form, "MEDIA_URL": settings.MEDIA_URL})

class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'Accounts/change_password.html'  
    success_url = reverse_lazy('AppAccounts:profile')  # Redirige al perfil después de cambiar la contraseña
    # Mensaje de éxito
    def form_valid(self, form):
        messages.success(self.request, "¡Contraseña cambiada con éxito!")
        return super().form_valid(form)

AppAccounts/templates/Accounts/change_password.html
{% extends 'base_login.html' %}
{% load static %}

{% block titulo %}Cambiar Contraseña{% endblock %}

{% block cuerpo %}
<div class="container my-8" style="margin-top: 20px; margin-bottom: 40px;"></div>
<div class="row justify-content-center">
  <div class="col-md-5"> 
    <div class="card shadow-lg">
      <div class="card-header bg-warning text-white">
        <h3 class="text-center">Cambiar Contraseña</h3>
      </div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          <div class="form-g">
            {{ form.old_password.label_tag }}
            {{ form.old_password }}
          </div>
          <p>* Su contraseña no puede asemejarse tanto a su otra información personal.</p>
          <p>* Su contraseña debe contener al menos 8 caracteres.</p>
          <p>* Su contraseña no puede ser una clave utilizada comúnmente.</p>
          <p>* Su contraseña no puede ser completamente numérica.</p>
          <div class="form-g">
            {{ form.new_password1.label_tag }}
            {{ form.new_password1 }}
          </div>
          <div class="form-g">
            {{ form.new_password2.label_tag }}
            {{ form.new_password2 }}
          </div>
          <div class="d-flex justify-content-end mt-3">
            <button type="submit" class="btn btn-warning m-2">Cambiar contraseña</button>
            <a href="{% url 'AppAccounts:profile' %}" class="btn btn-secondary m-2">Volver al perfil</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<p></p>
{% endblock %}

AppAccounts/templates/Accounts/edit_profile.html
{% extends 'base_perfil.html' %}
{% load static %}

{% block titulo %}Editar Perfil{% endblock %}

{% block cuerpo %}
<div class="container my-5">
  <div class="card shadow-lg">
    <div class="card-header bg-success text-white">
      <h1 class="text-center">Editar Usuario</h1>
    </div>
    <div class="card-body">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.first_name.label_tag }}
          {{ form.first_name }}
        </div>
        <div class="form-group">
          {{ form.last_name.label_tag }}
          {{ form.last_name }}
        </div>
        <p></p>
        <div class="form-group">
          {{ form.bio.label_tag }}
          {{ form.bio }}
        </div>
        <p></p>
        <div class="form-group">
          {{ form.birthday.label_tag }}
          {{ form.birthday }}
        </div>
        <div class="form-group">
          {{ form.address.label_tag }}
          {{ form.address }}
        </div>
        <div class="form-group">
          {{ form.phone.label_tag }}
          {{ form.phone }}
        </div>
        <p></p>
        <div class="form-group">
          <label>Selecciona tu avatar:</label>
          <p></p>
          <div class="avatar-selection">
            {% for value, label in form.fields.avatar.choices %}
              <label class="avatar-label">
                <input type="radio" name="avatar" value="{{ value }}" {% if form.avatar.value == value %}checked{% endif %}>
                <img src="{{ MEDIA_URL }}{{ value }}" alt="{{ label }}" class="avatar-img">
              </label>
            {% endfor %}
          </div>
        </div>

        <div class="justify-content-end mt-3">
          <button type="submit" class="btn btn-success me-2">Guardar cambios</button>
          <button href="{% url 'AppAccounts:profile' %}" class="btn btn-secondary m-2">Volver al perfil</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

AppAccounts/templates/Accounts/login.html
{% extends 'base_login.html' %}
{% load static %}

{% block titulo %}Iniciar sesión{% endblock %}

{% block cuerpo %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg">
        <div class="card-header bg-success text-white">
          <h3 class="text-center">Iniciar Sesión</h3>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              {{ form.username.label_tag }}
              {{ form.username }}
            </div>
            <div class="form-group">
              {{ form.password.label_tag }}
              {{ form.password }}
            </div>
            <div class="d-flex justify-content-end mt-3">
                <button type="submit" class="btn btn-success m-2">Iniciar sesión</button>
                <a href="{% url 'index' %}" class="btn btn-secondary m-2">Salir</a>
            </div>
          </form>
          <br>
          <p>¿No tienes cuenta? <a href="{% url 'AppAccounts:register' %}">Regístrate aquí</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

AppAccounts/templates/Accounts/profile.html
{% extends 'base_perfil.html' %}
{% load static %}

{% block titulo %}Perfil de Usuario{% endblock %}

{% block cuerpo %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card shadow-lg">
        <div class="card-header bg-success text-white">
          <h1 class="text-center">Perfil de {{ user.user.username }}</h1>
        </div>
        <div class="card-body">
          <div class="text-center mb-4">
            <img src="{{ user.avatar.url }}" alt="{{ user.user.username }}" class="rounded-circle" width="150">
          </div>
          <div class="mb-3">
            <h4 class="profile-text"><strong>Nombre:</strong> {{ user.user.first_name }} {{ user.user.last_name }}</h4>
          </div>
          <div class="mb-3">
            <h4 class="profile-text"><strong>Correo:</strong> {{ user.user.email }}</h4>
          </div>
          <div class="mb-3">
            <h4 class="profile-text"><strong>Biografía:</strong> {{ user.bio }}</h4>
          </div>
          <div class="mb-3">
            <h4 class="profile-text"><strong>Fecha de nacimiento:</strong> {{ user.birthday }}</h4>
          </div>
            <div class="d-flex justify-content-center"></div>
            <a href="{% url 'AppAccounts:edit_profile' %}" class="btn bg-success me-2">Editar Perfil</a>
            <a href="{% url 'AppAccounts:change_password' %}" class="btn btn-warning">Cambiar Contraseña</a>
            <a href="{% url 'AppAccounts:logout' %}" class="btn btn-danger m-2">Cerrar Sesión</a>
            <a href="{% url 'index' %}" class="btn btn-secondary">Regresar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

AppAccounts/templates/Accounts/signup.html
{% extends 'base_signup.html' %}
{% load static %}

{% block titulo %}Crear una cuenta{% endblock %}

{% block cuerpo %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg">
        <div class="card-header bg-success text-white">
          <h1 class="text-center">Crear Usuario</h1>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              {{ form.username.label_tag }}
              {{ form.username }}
            </div>
            <div class="form-group">
              {{ form.email.label_tag }}
              {{ form.email }}
            </div>
            <div class="form-group">
              {{ form.password1.label_tag }}
              {{ form.password1 }}
            </div>
            <div class="form-group">
              {{ form.password2.label_tag }}
              {{ form.password2 }}
            </div>
            <div class="d-flex justify-content-end mt-3">
              <button type="submit" class="btn btn-success m-2">Registrar Usuario</button>
              <a href="{% url 'index' %}" class="btn btn-secondary m-2">Salir</a>
            </div>
          </form>
          <br>
          <p>¿Ya tienes cuenta? <a href="{% url 'AppAccounts:login' %}">Inicia sesión aquí</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}